global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sip-server'
    static_configs:
      - targets: ['sip-server:8000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis doesn't expose HTTP metrics by default
  # To monitor Redis, use redis_exporter instead